name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Используйте ту версию, которую вы используете (можно 3.10, 3.11, 3.12)

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run linter (flake8)
        run: |
          flake8 src/

      - name: Run tests (pytest)
        run: |
          pytest src/tests/test_api.py -v